<?php

namespace Database\Seeders;

use App\Models\AdminStringSource;
use App\Models\AdminTranslationDefault;
use App\Models\Translation;
use App\Models\UiLocale;
use Illuminate\Database\Seeder;

/**
 * Seeds the admin UI translation data into the database:
 *
 *   1. admin_string_sources       — the registry of translatable strings
 *      (built from database/seeders/data/admin_strings.php, which is
 *      generated by `node scripts/extract-admin-strings.js`).
 *
 *   2. admin_translation_defaults — the factory default translations per
 *      locale (e.g. zh) shipped with the project.
 *
 *   3. translations               — the actual runtime translation rows for
 *      every UI locale. Values are only ever written into NEW or EMPTY rows:
 *      translations edited in the admin panel are NEVER overwritten.
 *
 * Usage: php artisan db:seed --class=AdminTranslationsSeeder
 */
class AdminTranslationsSeeder extends Seeder
{
    public const DEFAULT_LOCALE = 'en';
    public const INITIAL_LOCALES = ['en', 'zh'];

    public function run()
    {
        $this->seedUiLocales();

        $dataFile = __DIR__ . '/data/admin_strings.php';
        if (!is_file($dataFile)) {
            $this->command?->warn('database/seeders/data/admin_strings.php is missing — run "node scripts/extract-admin-strings.js" first.');

            return;
        }

        $data = require $dataFile;
        $sources = array_values(array_unique($data['sources'] ?? []));
        $defaults = $data['defaults'] ?? [];

        if (empty($sources)) {
            $this->command?->warn('The registry data file is empty — nothing to seed.');

            return;
        }

        $count = 0;
        $locales = UiLocale::orderBy('code')->pluck('code')->toArray();

        // 1) Registry table. Only ever add — strings removed from the codebase
        // stay in the registry so their translations are never orphaned.
        foreach ($sources as $source) {
            if (AdminStringSource::firstOrCreate(['source' => $source])->wasRecentlyCreated) {
                $count++;
            }
        }

        // 2) Factory default translations (upsert: this is shipped data, not
        // user data). The admin panel never writes to this table.
        foreach ($defaults as $locale => $map) {
            foreach ($map as $source => $value) {
                if (AdminTranslationDefault::updateOrCreate(
                    ['locale' => $locale, 'source' => $source],
                    ['value' => $value]
                )->wasRecentlyCreated) {
                    $count++;
                }
            }
        }

        // 3) Runtime translation rows per UI locale.
        foreach ($locales as $locale) {
            foreach ($sources as $source) {
                $value = $locale === self::DEFAULT_LOCALE
                    ? $source
                    : ($defaults[$locale][$source] ?? null);

                $row = Translation::firstOrCreate(
                    ['locale' => $locale, 'source' => $source],
                    ['value' => $value]
                );

                if ($row->wasRecentlyCreated) {
                    $count++;
                    continue;
                }

                // Fill empty rows only — never overwrite translations the
                // user already set in the admin panel.
                if (($row->value === null || $row->value === '') && $value !== null) {
                    $row->update(['value' => $value]);
                    $count++;
                }
            }
        }

        $this->command?->info("Seeded {$count} new/updated rows (" . count($sources) . ' strings x ' . count($locales) . ' locales + registry/defaults).');
    }

    /**
     * The admin UI languages (managed from Settings → Localization).
     */
    protected function seedUiLocales(): void
    {
        foreach (self::INITIAL_LOCALES as $i => $code) {
            UiLocale::firstOrCreate(
                ['code' => $code],
                [
                    'name' => $code === 'en' ? 'English' : ($code === 'zh' ? '中文' : strtoupper($code)),
                    'is_default' => $code === self::DEFAULT_LOCALE,
                ]
            );
        }

        // Make sure exactly one default exists.
        if (UiLocale::where('is_default', true)->count() === 0) {
            UiLocale::where('code', self::DEFAULT_LOCALE)->update(['is_default' => true]);
        }
    }
}
